### ISSUE TITLE
KEY_CODE tests are not running on a valid app

### ISSUE THREAD

**Issue by arun-madhavan-013** [device-automation-bus/dab-compliance-suite#28]
While running the compliance suite; it directly starts the KEY INPUT tests irrespective of where the user is on device UI.
It would be great if we can ask the user to launch a KEYCODE printing app or browser instance with url https://keycode.info or similar webpage which will display the received KEYCODE so that user can confirm the received KEYCODE.

**Comment by bgy36ww** [comment]
But the problem is that we don't know what's the system browser app? How do we know such app exists?

**Comment by arun-madhavan-013** [comment]
From DAB Spec perspective; agree that it is not required.
From an integration & validation perspective this helps.
There is nothing to be done at this point considering these. Hence closing this issue.
