### ISSUE TITLE
How should devices that do not support HDMI output handle the hdrOutputMode property of the system/setttings topic?

### ISSUE THREAD

**Issue by daehyunpark** [device-automation-bus/dab-compliance-suite#31]
https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#operation-list-system-settings
enum HdrOutputMode {
    // Always output HDMI signal in HDR Format
    AlwaysHdr = "AlwaysHdr",
    // Output HDMI signal in HDR Format Only when playing HDR content
    HdrOnPlayback = "HdrOnPlayback",
    // Never Output HDMI Signal in HDR Mode
    DisableHdr = "DisableHdr",
}

In the DAB 2.0 documentation, the HdrOutputMode property is defined only for HDMI output.
Typically, TVs do not support HDMI output.
I interpreted the HdrOutputMode property as Hdr content playback ability,
So I gave it the HdrOnPlayback value.
As a result, SystemSettingsSetHdroutputmode TV fails.

I have a few questions regarding this.
1. Is the HdrOutputMode property limited to HDMI output?
2. What should I do if it does not support HDMI output?
3. Can I handle this property depending on whether HDR content is played or not?
4.If I do not support this property, can I omit it?
5. By any chance, does Disabled ("Never Output HDMI Signal in HDR Mode) mean a device that does not support HDMI output?

In any case, this TC will fail on TV.

**Comment by bgy36ww** [comment]
I think you can just return not supported as response. 
I will work in the mean time to support this feature. For YouTube Certification, just explain it when you upload the result. I don't think YouTube would expect everything to be passed.
