### ISSUE TITLE
Conformance Test Suite should remove "v=" in the contentId string for deep link launch

### ISSUE THREAD

**Issue by vryadlapalli** [device-automation-bus/dab-compliance-suite#8]
The content-id should pass as it is without prepending the "v=". 

Some of the channels & platforms also needed the mediaType for deep link launches. You could allow the mediaType parameter as well.

**Comment by daehyunpark** [comment]
Hi @vryadlapalli 
Does this mean I can pass the Conformance Test Suite by adding "v="?
